server:
  port: 8601
eureka:
  instance:
    hostname: localhost
    appname: eureka-server
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:${server.port}/eureka/

