eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8601/eureka/
spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
server:
  port: 8750 #Æô¶¯¶Ë¿Ú
